### ISSUE TITLE
Easier way to get the MFC model ID

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/mfc_cb.node#1]
There is an easier way to get the broadcaster ID for MFC than viewing the source:
- click the "Send a tip" and you get an url like http://www.myfreecams.com/php/tip.php?request=tip&broadcaster_id=15541706&cache_id=0.6530122208520828&night_mode=1
The broadcaster ID is indicated by the broadcaster_id variable (15541706 is this case)

Also the provided config.yml file is invalid as is. You need to remove lines 17-23 and 32.

**Comment by jrudess** [comment]
Drafted a new release 0.2.2 with fixes to the master branch config.yml to correct the unresolved merge conflicts.    

The broadcaster ID is stored in config.yml in order to track models across name changes.  However, when adding or removing a model by using updates.yml, the model name is used instead of broadcaster ID, so manual lookups are not necessary when using updates.yml.
