### ISSUE TITLE
High CPU Usage (macOS) & other issues

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/mfc_cb.node#38]
First of all, I would like to thank you and everyone that contributes to this project, I really appreciate your hard work.

Anyways, there are few issues I've come across some of which only affect current version and one which I also affected previous version. 

The first issue relates to cpu usage, affecting only the current version. With the previous version my cpu usage for node was (is) approx 0-1% while waiting and on average 3.5% when it refreshes. However, with current version the cpu usage spikes up to around 40% when it refreshes, which in return is making my laptop quite hot. 

second issue is a minor but annoying issue, affecting only the current version. basically after the script has been running for quite some time, it doesnt let you stop it using control-C so instead you need to close the entire terminal.

final issue relates to issue mentioned here: https://github.com/jrudess/mfc_cb.node/issues/37 and it seems like you have already found a solution so it should fix the problem. This actually existed on previous version too as well as for fanout96's previous version. I can't comment on this issue for current version as from experience it seems like the problem only gets worse after you've had the script running for long period of time and from there onwards it then starts getting worse over time i.e it occurs more frequently .

Thanks once again

**Comment by jrudess** [comment]
@Asynchr0nous Thanks for the feedback on cpu usage.  I'm not surprised that there has been an increase with the new UI.   Hopefully we can mitigate this through some restructuring or optimizations on my part.

Can you try running with the lists hidden which is mostly like the original log-only mode?  I'm curious about a couple things:

To hide the list, hit enter to focus the blue bar at the bottom then type "hide list".   Or you can set listshown to false in config.yml.

Also, does this happen immediately on a fresh start?  Or does processing increase only after its been running for a while?

I believe the ctrl-c issue might have a couple causes.  I haven't had this happen to me reliably enough to know what's going on just yet:

1) If the cursor is currently focused in the blue bar at the bottom, ctrl+c input might not be getting captured correctly.   If nothing happens, I usually check to see if there is a cursor in the blue input bar on the bottom, and if so then hit esc to remove focus, and hit ctrl+c again.

2) When step 1 doesn't work, please check if there are any ffmpeg processes still running when ctrl+c didn't work.   If there are try killing them by hand, and then see if the script ends.

There is a behavior change in the latest version due to the Blessed UI library intercepting ctrl+c.  Previously, I would capture ctrl+c, but it was automatically passed down to children processes, so every time you hit ctrl+c it would get sent to ffmpeg.   Sometimes one ctrl+c is not enough to kill ffmpeg.

But in my code, the ctrl+c handler has protection logic to only process 1 ctrl+c and ignore any more that  come.  So I think I'm dropping the additional ctrl+c's that come in and not passing them to ffmpeg, and then shutdown hangs.

BTW, I am moving the project to https://github.com/jrudess/streamdvr

All bug fixes will be happening there, and I'm going to deprecate this repo.  Decided to rename things a little after adding twitch support as the mfc_cb name was a bit limiting. :-)

**Comment by fanout96** [comment]
To simplify the work with ffmpeg, you can use "fluent-ffmpeg" to handle errors and easily kill the video recording process

**Comment by Asynchr0nous** [comment]
@jrudess i disabled the list option on intial setup so that shouldn't be an issue. the cpu usgage only seems to increase when it scans for models (in my case every 15 seconds, which i used on previous version too) and it happens soon as I start. If you keep eye on your activity monitor, you'll see that cpu usage will hit 40%+ for few seconds and then come down to about 1% and repeat.

Weirdly, I didnt seem to have the ctrl-c issue at all today and now that you mentioned that it could be due to the cursor being focused in blue bar, I tested it and that is indeed the case. focusing on blue bar doesn't capture ctrl-c at all for me. I think i must have accidently focused on blue bar at some point yesterday.

off topic but were there any particular reasons for changing the UI?

**Comment by jrudess** [comment]
I'm not happy with the way focus behaves in the new UI, and that is likely to change as I learn the new library better.  I also hate that I can't copy/select log text directly from the terminal now, so I redirect the log to a file now in streamdvr repo until I can figure out the fix.

I do see a jump, but I'm running this on a 4ghz desktop, so the numbers scale a bit differently. 
 It usually rests at 0.7% cpu, and then jumps to 4-7% when the scans kick in.  So I'll be able to tell when I make large improvements, but incremental ones will be a bit tougher to see.   

I can implement a stagger timer, to prevent MFC, CB, Twitch lookups from all occurring simultaneously 
 (except for initial startup).   This doesn't fix the problem, but if both mfc/cb are processing simultaneously and that takes you to 40%, maybe we can limit to 20% if only one is processing at a time.

As for the interface changes, I wanted a better way to quickly see my full model list, and with UIDs in config.yml that is difficult.  Also, I found myself using 'ps aux | grep ffmpeg' a lot to see how many caps are going, and now I can see that with a quick glance.

But most of my plans with the new interface haven't started yet.  I want to get rid of updates.yml and be able to add/remove models from the new cli interface at runtime.  I'd like to be able to navigate the sites/streamers with cursor/mouse to pause/resume individual streams,  or look up more metadata info that can be pulled from the server (room topic, counts, online time, etc).

**Comment by Asynchr0nous** [comment]
I didn't want to sound ungrateful so didnt mention about not being able to copy/select from terminal.

I only have chaturbate enabled as I use horacio9a's script for recording due to freezing issue when using ffmpeg So that 40% cpu is just for CB. I have 55 models in chaturbate list right now and at any given time i usually don't see more than 3 models recording at same time (rarely hits more than 3). My cpu usage was pretty much same as yours prior to this version with same amount models in my config file. 

I'm not gonna lie but the updates.yml is one of the best thing about the script. some of the new features you mentioned do sound good but IMHO it would only be worth it if isn't resource hungry.

**Comment by fanout96** [comment]
In my repo, there is a "Chunker" - I wrote it to upload individual chunks and splicing it into a single file, but the code is not much good, although it performs its functions.
The advantage of this script is its very low resource consumption

**Comment by jrudess** [comment]
Can you pull from my experiments branch and see if CPU usage decreases now?  

In the older versions, CB pages were fetched sequentially.   In the new version, a different page is fetched fore very model in the list simultaneously on each interval.  

The patch in the experiments re-serializes CB fetches which will slow down the update interval a bit, but I think it should help with keeping CPU usage low.

**Comment by Asynchr0nous** [comment]
So I downloaded this https://github.com/jrudess/streamdvr/tree/experiments and gave it a try. 

Results: CPU seems to be back to normal but it is EXTREMELY slow. Takes few mins to scan all models. I don't know what has changed but even though you say the previous versions scanned sequentially, it was really fast so setting interval to say 15 seconds took 15seconds + maybe another 5 seconds if you added another model. I will give your streamdvr master script and see if that changes anything.

**Comment by jrudess** [comment]
Yeah, it can definitely get better, but the crux of the issue appears to be sending out 55 json fetch requests to CB simultaneously.  I don't think it is specific to the new UI, that just happened to come at the same time as CB changes.

What I'll do is add a new config option for how many to batch at a time.   If you set it to 0, it will have no limit, if you set it to 1, then it will behave like the experiments branch.   Probably a setting like 10 would work well.

**Comment by jrudess** [comment]
The new option in config.yml is cbBatchSize.  I've defaulted it to 10, but you can fine tune it and see how it works out.   jrudess/streamdvr#3c9f7dd6662644acbb72bffd1c2faf6af36e08f8

**Comment by jrudess** [comment]
streamdvr v0.6.3 has all of the improvements from this thread so far.  There's definitely lots of room for improvements, but please file new issues in the streamdvr repo.
