### ISSUE TITLE
ffmgeg and streaming bandwidth

### ISSUE THREAD

**Issue by forsomefun** [jrudess/mfc_cb.node#5]
Thanks For making this program. It is the most up to date, and from all the ones I have used it takes the least effort from the user after setting up. 
Would ffmgeg64 bit provide any benefit to the program?

Also are you aware of how much  bandwidth it takes to record one highest quality MFC model or CB model?

**Comment by jrudess** [comment]
I'm in linux and am only using the 64-bit ffmpeg.  I don't know that there would be any benefit one way or the other.

The bandwidth used is roughly just the final mp4 filesize.   There are container differences since the feed is not an mp4 stream and only gets converted to mp4.  I can't say whether the real consumed bandwidth is slightly more or slightly less than the final mp4 file size, but I think it would be pretty close.
